language: java
jdk:
  - openjdk8

branches:
  only:
    - deploy

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pcn021152@gmail.com

before_deploy:
  - zip -r photo-tag-backend *
  - mkdir -p deploy
  - mv photo-tag-backend.zip deploy/photo-tag-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: buildzip-spring #s3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deployed: true
