language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pcn021152@gmail.com

before_deploy:
  - zip -r photo-tag-backend *
  - mkdir -p deploy
  - mv photo-tag-backend.zip deploy/photo-tag-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: buildzip-spring #s3 bucket
    region: ap-northeast-2
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: buildzip-spring
    key: photo-tag-backend.zip
    bundle_type: zip #압축 확장자
    application: photo-tag-backend #등록한 CodeDeploy 애플리케이션
    deployment_group: photo-tag-backend-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true
